name: Fetch and Prepare Data

on:
  push:
    branches:
      - main

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install -y wget gzip tar

      - name: Download TAR file via FTP
        run: |
          wget ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE171nnn/GSE171524/suppl/GSE171524_RAW.tar
          tar -xf GSE171524_RAW.tar -C ./data

      - name: Decompress .gz files
        run: |
          find ./data -name "*.gz" -exec gunzip {} \;
          
      - name: Commit and push data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/
          git commit -m "Fetched and extracted data"
          git push
