name: Data Fetch Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Download the TAR file via FTP
      - name: Download TAR file from FTP
        run: |
          apt-get update && apt-get install -y ftp
          ftp -inv ftp.ncbi.nlm.nih.gov <<EOF
          user anonymous ""
          cd /geo/series/GSE171nnn/GSE171524/suppl/
          get GSE171524_RAW.tar
          bye
          EOF
        shell: bash

      # Step 2: Extract the TAR file
      - name: Extract TAR file
        run: |
          tar -xvf GSE171524_RAW.tar -C ./GSE171524_RAW
        shell: bash

      # Step 3: Unzip the .csv.gz files
      - name: Decompress .csv.gz files
        run: |
          find ./GSE171524_RAW -name "*.gz" -exec gunzip {} \;
        shell: bash

      # Step 4: Upload the files as an artifact (optional)
      - name: Upload decompressed files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: decompressed-data
          path: ./GSE171524_RAW

