name: Run scRNAseq Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scanpy scvi-tools seaborn pandas numpy scipy matplotlib diffxpy decoupler

    - name: Ensure data directory exists
      run: mkdir -p ./data

    - name: Extract GSE171524_RAW.tar
      run: tar -xvf ./data/GSE171524_RAW.tar -C ./data/
      continue-on-error: true  # Continue even if this step fails

    - name: Verify GSE171524_RAW directory exists
      run: ls -l ./data/GSE171524_RAW

    - name: Run scRNAseq Analysis
      run: |
        python scRNAseq_Analysis_v4.py

    - name: Upload analysis outputs
      uses: actions/upload-artifact@v3
      with:
        name: analysis-images
        path: ./output/
